SCRIPT_NAME=elf
OUTPUT_FORMAT=elf32-i386
TEXT_START_ADDR=0x10000000
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
COMMONPAGESIZE="CONSTANT (COMMONPAGESIZE)"
ARCH=i386
MACHINE=
NOP=0x90909090
TEMPLATE_NAME=elf32
GENERATE_SHLIB_SCRIPT=yes
GENERATE_PIE_SCRIPT=yes
NO_SMALL_DATA=yes
SEPARATE_GOTPLT=12

#if [ "x${host}" = "x${target}" ]; then
#  case " $EMULATION_LIBPATH " in
#    *" ${EMULATION_NAME} "*)
#      NATIVE=yes
#  esac
#fi

